export type Element = {number:number;symbol:string;name:string;row:number;col:number;category:string};
const symbols="H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og".split(" ");
const names="수소 헬륨 리튬 베릴륨 붕소 탄소 질소 산소 플루오린 네온 나트륨 마그네슘 알루미늄 규소 인 황 염소 아르곤 칼륨 칼슘 스칸듐 타이타늄 바나듐 크로뮴 망가니즈 철 코발트 니켈 구리 아연 갈륨 저마늄 비소 셀레늄 브로민 크립톤 루비듐 스트론튬 이트륨 지르코늄 나이오븀 몰리브데넘 테크네튬 루테늄 로듐 팔라듐 은 카드뮴 인듐 주석 안티모니 텔루륨 아이오딘 제논 세슘 바륨 란타넘 세륨 프라세오디뮴 네오디뮴 프로메튬 사마륨 유로퓸 가돌리늄 터븀 디스프로슘 홀뮴 어븀 툴륨 이터븀 루테튬 하프늄 탄탈럼 텅스텐 레늄 오스뮴 이리듐 백금 금 수은 탈륨 납 비스무트 폴로늄 아스타틴 라돈 프랑슘 라듐 악티늄 토륨 프로트악티늄 우라늄 넵투늄 플루토늄 아메리슘 퀴륨 버클륨 캘리포늄 아인슈타이늄 페르뮴 멘델레븀 노벨륨 로렌슘 러더포듐 더브늄 시보귬 보륨 하슘 마이트너륨 다름슈타튬 뢴트게늄 코페르니슘 니호늄 플레로븀 모스코븀 리버모륨 테네신 오가네손".split(" ");
export const categories: Record<string,{name:string;background:string;ink:string}> = {
 nonmetal:{name:"비금속",background:"#e2eeff",ink:"#4774b6"},halogen:{name:"할로젠",background:"#e2f3eb",ink:"#388d73"},noble:{name:"비활성 기체",background:"#ebe5fa",ink:"#9070bb"},alkali:{name:"알칼리 금속",background:"#fbe7e9",ink:"#ba6373"},alkaline:{name:"알칼리 토금속",background:"#fff0db",ink:"#b38a46"},transition:{name:"전이 금속",background:"#f9e9dc",ink:"#b7865d"},post:{name:"기타 금속",background:"#e5edf0",ink:"#6f929e"},metalloid:{name:"준금속",background:"#e3f0df",ink:"#6c965a"},lanthanide:{name:"란타넘족",background:"#eee7f7",ink:"#9b7ab3"},actinide:{name:"악티늄족",background:"#f4e2ed",ink:"#b47d9b"}
};
export const ELEMENTS:Element[]=symbols.map((symbol,i)=>{const n=i+1;let row=1,col=1;if(n===2)col=18;else if(n>=3&&n<=10){row=2;col=n<5?n-2:n+8;}else if(n>=11&&n<=18){row=3;col=n<13?n-10:n;}else if(n>=19&&n<=36){row=4;col=n-18;}else if(n>=37&&n<=54){row=5;col=n-36;}else if(n>=55&&n<=86){row=6;col=n<=56?n-54:n>=72?n-68:3;}else if(n>=87){row=7;col=n<=88?n-86:n>=104?n-100:3;}if(n>=57&&n<=71){row=9;col=n-54;}if(n>=89&&n<=103){row=10;col=n-86;}
 let category=col===1?"alkali":col===2?"alkaline":col===18?"noble":col===17?"halogen":col>=3&&col<=12?"transition":"post";
 if([1,6,7,8,15,16,34].includes(n))category="nonmetal";if([5,14,32,33,51,52].includes(n))category="metalloid";if(n>=57&&n<=71)category="lanthanide";if(n>=89&&n<=103)category="actinide";
 return {number:n,symbol,name:names[i],row,col,category};});
export const elementBySymbol=Object.fromEntries(ELEMENTS.map(e=>[e.symbol,e]));
export function atomColors(symbol:string){if(symbol==="H")return {background:"#ffffff",ink:"#74768e",stroke:"#dddfe9"};if(symbol==="O")return {background:"#fff0ed",ink:"#d97669",stroke:"#f0c3b8"};if(symbol==="C")return {background:"#ebe9f3",ink:"#595569",stroke:"#cbc7db"};if(symbol==="N")return {background:"#e8edff",ink:"#6b79c3",stroke:"#c0caee"};const c=categories[elementBySymbol[symbol]?.category||"nonmetal"];return {...c,stroke:c.ink+"66"};}
