"use client";
import { useEffect, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from "react";
import { Atom as AtomIcon, ArrowDownLeft, ArrowRight, BookOpen, Check, CircleHelp, FlaskConical, Lightbulb, Link2, Loader2, LockKeyhole, MousePointer2, Plus, RotateCcw, Search, Sparkles, Trash2, Unlink, X, HardDrive, TriangleAlert, Volume2, VolumeX, Rotate3D } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { MOLECULES, components, matchMolecule, connect, canConnect, removeAtoms, valences, removeComponent, type Graph, type Molecule } from "@/lib/chemistry";
import { ELEMENTS, categories, elementBySymbol, atomColors } from "@/lib/elements";
import { geometryLabel, arrangeMolecule } from "@/lib/geometry";
import { MOLECULE_INFO, infoSources } from "@/lib/molecule-info";
import { hintText, HINT_TITLES } from "@/lib/hints";
import { configureSound, unlockSound, playPop, playDiscovery } from "@/lib/sounds";
import { MoleculeViewer } from "@/components/molecule-viewer";
import { HintSteps } from "@/components/hint-steps";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import "./lab.css";
import { IonicLab } from "@/components/ionic-lab";
import { IONIC_COMPOUNDS } from "@/lib/ionic";
import { claimFirstDiscovery } from "@/lib/discovery-feedback";
import { useCollectionFocus } from "@/components/use-collection-focus";
import { IsomerFamily } from "@/components/isomer-family";
import { SubstancePhoto } from "@/components/substance-photo";
import { isomerFamily, molecularFormula } from "@/lib/isomers";
import { Fireworks } from "@/components/fireworks";
const EMPTY:Graph={atoms:[],bonds:[]};
import { collectionKey, readCollection, saveLocalDiscovery, type Discovery } from "@/lib/local-collection";
const STORAGE_KEY=collectionKey(window.location.pathname);
type Celebration={molecule:Molecule;key:string};
type ModelTool={name:string;description:string;inputSchema:object;execute:(args:Record<string,unknown>)=>Promise<unknown>|unknown;annotations?:{readOnlyHint:boolean}};
type ModelContext={registerTool:(tool:ModelTool,options?:{signal?:AbortSignal})=>void|Promise<void>};
function MiniMolecule({symbols=["H","O","H"],large=false}:{symbols?:string[];large?:boolean}){return <div className={`mini-molecule ${large?"large":""}`} aria-hidden="true">{symbols.slice(0,4).map((s,i)=><span key={i} style={{background:atomColors(s).background,color:atomColors(s).ink,borderColor:atomColors(s).stroke}}>{s}</span>)}</div>}
export default function Lab(){
 const [labMode,setLabMode]=useState<"covalent"|"ionic">("covalent");const [ionicCollectionOpen,setIonicCollectionOpen]=useState(false);const [ionicCount,setIonicCount]=useState(0);
 const [graph,setGraph]=useState<Graph>(EMPTY);const graphRef=useRef<Graph>(EMPTY);
 const [selected,setSelected]=useState<string|null>(null);const [bondMode,setBondMode]=useState(false);const [hoverSymbol,setHoverSymbol]=useState("O");
 const [showCollection,setShowCollection]=useState(false);const [showHelp,setShowHelp]=useState(false);const [showClear,setShowClear]=useState(false);
 const [search,setSearch]=useState("");const [catalogFilter,setCatalogFilter]=useState<"all"|"found"|"isomers">("all");const [detail,setDetail]=useState<Molecule|null>(null);
 const [saved,setSaved]=useState<Record<string,Discovery>>({});const savedRef=useRef<Record<string,Discovery>>({});const [pending,setPending]=useState<Record<string,Graph>>({});const pendingRef=useRef<Record<string,Graph>>({});
 const [loading,setLoading]=useState(true);const [saveError,setSaveError]=useState<string|null>(null);const [saving,setSaving]=useState(0);
 const [celebration,setCelebration]=useState<Celebration|null>(null);const [queue,setQueue]=useState<Celebration[]>([]);const celebrated=useRef(new Set<string>());const inFlight=useRef(new Set<string>());const announced=useRef(new Set<string>());
 const [collectionTarget,setCollectionTarget]=useState<string|null>(null);const collectionGridRef=useCollectionFocus(showCollection,collectionTarget,!loading);
 function openDiscoveredCollection(id:string){setCollectionTarget(id);setSearch("");setCatalogFilter("all");setCelebration(null);setQueue([]);setShowCollection(true);}
 const [hint,setHint]=useState<Molecule>(MOLECULES[0]);const [hintLevels,setHintLevels]=useState<Record<string,number>>({});
 const [modelMolecule,setModelMolecule]=useState<Molecule|null>(null);const [settling,setSettling]=useState(false);
 const [soundOn,setSoundOn]=useState(true);const [soundVolume,setSoundVolume]=useState(.18);const [soundReady,setSoundReady]=useState(false);
 const hintLevel=hintLevels[hint.id]||0;
 function advanceHint(m:Molecule){setHintLevels(levels=>({...levels,[m.id]:Math.min(4,(levels[m.id]||0)+1)}));}
 function nextChallenge(){const next=MOLECULES.find(m=>!savedRef.current[m.id]&&!pendingRef.current[m.id]&&m.id!==hint.id)||MOLECULES[(MOLECULES.indexOf(hint)+1)%MOLECULES.length];setHint(next);}
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('alchemist-sound-v1')||'null');if(value&&typeof value.enabled==='boolean'&&typeof value.volume==='number'&&Number.isFinite(value.volume)){setSoundOn(value.enabled);setSoundVolume(Math.max(0,Math.min(.35,value.volume)));}}catch{}setSoundReady(true);},[]);
 useEffect(()=>{configureSound(soundOn,soundVolume);if(soundReady)try{localStorage.setItem('alchemist-sound-v1',JSON.stringify({enabled:soundOn,volume:soundVolume}));}catch{}},[soundOn,soundVolume,soundReady]);
 useEffect(()=>{if(celebration)playDiscovery();},[celebration]);
 useEffect(()=>{if(!settling)return;const timer=window.setTimeout(()=>setSettling(false),650);return()=>window.clearTimeout(timer);},[settling]);const [dragging,setDragging]=useState(false);const [near,setNear]=useState<string|null>(null);
 const svg=useRef<SVGSVGElement>(null);const drag=useRef<{id:string;startX:number;startY:number;origin:Graph;ids:Set<string>;moved:boolean}|null>(null);
 function updateGraph(g:Graph){graphRef.current=g;setGraph(g);}
 async function loadCollection(){setLoading(true);try{const values=readCollection(window.localStorage,STORAGE_KEY);savedRef.current=values;setSaved(values);setSaveError(null);}catch(e){setSaveError(e instanceof Error?e.message:"브라우저 저장 설정을 확인해 주세요.");}finally{setLoading(false);}}
 async function saveDiscovery(id:string,g:Graph){if(savedRef.current[id]||inFlight.current.has(id))return;pendingRef.current={...pendingRef.current,[id]:g};setPending(pendingRef.current);inFlight.current.add(id);setSaving(v=>v+1);
  try{const values=saveLocalDiscovery(window.localStorage,STORAGE_KEY,g);savedRef.current=values;setSaved(values);const copy={...pendingRef.current};delete copy[id];pendingRef.current=copy;setPending(copy);setSaveError(null);}catch(e){setSaveError(e instanceof Error?e.message:"브라우저 저장 설정을 확인해 주세요.");}finally{inFlight.current.delete(id);setSaving(v=>v-1);}
 }
 async function retrySaving(){await loadCollection();for(const [id,g] of Object.entries(pendingRef.current)){if(savedRef.current[id]){const copy={...pendingRef.current};delete copy[id];pendingRef.current=copy;setPending(copy);}else await saveDiscovery(id,g);}}
 useEffect(()=>{void loadCollection();const sync=(event:StorageEvent)=>{if(event.key===STORAGE_KEY||event.key===null)void retrySaving();};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync);},[]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(Object.keys(pendingRef.current).length){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[]);
 useEffect(()=>{if(!celebration&&queue.length){setCelebration(queue[0]);setQueue(q=>q.slice(1));}},[celebration,queue]);
 function process(g:Graph){
 const nextBonds:Graph["bonds"]=[];const discoveries:Celebration[]=[];let arranged=g;let didArrange=false;
 for(const c of components(g)){
  const result=matchMolecule({...c,bonds:c.bonds.map(b=>({...b,order:1}))});
  if(!result){nextBonds.push(...c.bonds);continue;}
  nextBonds.push(...result.bonds);const normalized={...c,bonds:result.bonds};
  const key=result.molecule.id+":"+c.atoms.map(a=>a.id).sort().join(",");
  if(!celebrated.current.has(key)){celebrated.current.add(key);arranged=arrangeMolecule(arranged,result.molecule,result.atomIds);didArrange=true;}
  if(claimFirstDiscovery(result.molecule.id,savedRef.current,pendingRef.current,announced.current))discoveries.push({molecule:result.molecule,key});
  void saveDiscovery(result.molecule.id,normalized);
 }
 updateGraph({...arranged,bonds:nextBonds});if(didArrange)setSettling(true);if(discoveries.length)setQueue(q=>[...q,...discoveries]);}

 function summon(symbol:string,count=1){if(!elementBySymbol[symbol])return {ok:false,error:"알 수 없는 원소입니다."};const current=graphRef.current;if(current.atoms.length+count>40){toast("작업대에는 원자를 40개까지 놓을 수 있어요.");return {ok:false,error:"원자 한도 초과"};}const atoms=Array.from({length:count},(_,i)=>{const index=current.atoms.length+i;return {id:crypto.randomUUID(),symbol,x:130+(index%6)*98,y:130+(Math.floor(index/6)%4)*95};});updateGraph({...current,atoms:[...current.atoms,...atoms]});setSelected(atoms[atoms.length-1].id);setHoverSymbol(symbol);setBondMode(false);playPop();if(!valences[symbol])toast(`${elementBySymbol[symbol].name}: 소환할 수 있지만, 현재 도감에는 포함되지 않아요.`);return {ok:true,atomIds:atoms.map(a=>a.id)};}
 function attach(a:string,b:string){const next=connect(graphRef.current,a,b);if(!next){toast("이 연결은 만들 수 없어요. 결합 수나 이미 연결된 원자를 확인해 주세요.");return {ok:false};}process(next);setBondMode(false);return {ok:true,graphUpdated:true,collectionSave:"asynchronous; check get_lab_state for saved/pending"};}
 function remove(ids:string[]){process(removeAtoms(graphRef.current,ids));setSelected(null);setBondMode(false);return {ok:true};}
 function deleteGroup(id:string){const before=graphRef.current;const group=components(before).find(c=>c.atoms.some(a=>a.id===id));if(!group)return;updateGraph(removeComponent(before,id));setSelected(null);setBondMode(false);toast(group.atoms.length>1?`연결된 원자 ${group.atoms.length}개를 함께 삭제했어요.`:"원자를 삭제했어요.");}
 function summonMolecule(m:Molecule){if(!savedRef.current[m.id]&&!pendingRef.current[m.id])return;const current=graphRef.current;if(current.atoms.length+m.atoms.length>40){toast("작업대를 조금 비워 주세요. 원자는 40개까지 놓을 수 있어요.");return;}const atoms=m.atoms.map(symbol=>({id:crypto.randomUUID(),symbol,x:400,y:260}));const bonds=m.edges.map(([a,b,order])=>({a:atoms[a].id,b:atoms[b].id,order}));const placed=arrangeMolecule({atoms,bonds},m,atoms.map(a=>a.id));celebrated.current.add(m.id+":"+atoms.map(a=>a.id).sort().join(","));updateGraph({atoms:[...current.atoms,...placed.atoms],bonds:[...current.bonds,...placed.bonds]});setSelected(atoms[0].id);setDetail(null);setShowCollection(false);setModelMolecule(null);setBondMode(false);playPop();}
 function moveGroup(id:string,dx:number,dy:number){const g=graphRef.current;const group=components(g).find(c=>c.atoms.some(a=>a.id===id));if(!group)return;const ids=new Set(group.atoms.map(a=>a.id));dx=Math.max(35-Math.min(...group.atoms.map(a=>a.x)),Math.min(765-Math.max(...group.atoms.map(a=>a.x)),dx));dy=Math.max(35-Math.min(...group.atoms.map(a=>a.y)),Math.min(525-Math.max(...group.atoms.map(a=>a.y)),dy));updateGraph({...g,atoms:g.atoms.map(a=>ids.has(a.id)?{...a,x:a.x+dx,y:a.y+dy}:a)});}
 function detach(id:string){const g=graphRef.current;process({...g,bonds:g.bonds.filter(b=>b.a!==id&&b.b!==id)});setBondMode(false);}
 function clear(){updateGraph(EMPTY);setSelected(null);setBondMode(false);setNear(null);toast("작업대를 비웠어요. 발견한 분자는 도감에 남아 있어요.");}
 function point(event:ReactPointerEvent<SVGElement>){const node=svg.current!;const p=node.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const transformed=p.matrixTransform(node.getScreenCTM()!.inverse());return {x:transformed.x,y:transformed.y};}
 function startDrag(event:ReactPointerEvent<SVGGElement>,id:string){if(event.button!==0)return;setSettling(false);unlockSound();event.stopPropagation();if(bondMode&&selected&&selected!==id){attach(selected,id);return;}setSelected(id);const p=point(event);const g=graphRef.current;const group=components(g).find(c=>c.atoms.some(a=>a.id===id))!;drag.current={id,startX:p.x,startY:p.y,origin:g,ids:new Set(group.atoms.map(a=>a.id)),moved:false};event.currentTarget.setPointerCapture(event.pointerId);setDragging(true);}
 function moveDrag(event:ReactPointerEvent<SVGGElement>){const d=drag.current;if(!d)return;const p=point(event);let dx=p.x-d.startX,dy=p.y-d.startY;if(Math.hypot(dx,dy)>3)d.moved=true;const group=d.origin.atoms.filter(a=>d.ids.has(a.id));dx=Math.max(35-Math.min(...group.map(a=>a.x)),Math.min(765-Math.max(...group.map(a=>a.x)),dx));dy=Math.max(35-Math.min(...group.map(a=>a.y)),Math.min(525-Math.max(...group.map(a=>a.y)),dy));const next={...d.origin,atoms:d.origin.atoms.map(a=>d.ids.has(a.id)?{...a,x:a.x+dx,y:a.y+dy}:a)};updateGraph(next);const active=next.atoms.find(a=>a.id===d.id)!;const candidate=next.atoms.filter(a=>!d.ids.has(a.id)&&canConnect(next,d.id,a.id)).sort((a,b)=>Math.hypot(a.x-active.x,a.y-active.y)-Math.hypot(b.x-active.x,b.y-active.y))[0];setNear(candidate&&Math.hypot(candidate.x-active.x,candidate.y-active.y)<105?candidate.id:null);}
 function endDrag(event:ReactPointerEvent<SVGGElement>,cancel=false){const d=drag.current;if(!d)return;drag.current=null;setDragging(false);setNear(null);if(cancel){updateGraph(d.origin);return;}const g=graphRef.current;const a=g.atoms.find(a=>a.id===d.id);if(!a||!d.moved)return;const dropPoint=point(event);if(dropPoint.x>690&&dropPoint.y>470){deleteGroup(a.id);return;}const candidate=g.atoms.filter(b=>!d.ids.has(b.id)&&canConnect(g,a.id,b.id)).sort((b,c)=>Math.hypot(b.x-a.x,b.y-a.y)-Math.hypot(c.x-a.x,c.y-a.y))[0];if(candidate&&Math.hypot(candidate.x-a.x,candidate.y-a.y)<105){const dx=a.x-candidate.x,dy=a.y-candidate.y;const length=Math.hypot(dx,dy);const ux=length>1?dx/length:-1,uy=length>1?dy/length:0;const sx=candidate.x+ux*88-a.x,sy=candidate.y+uy*88-a.y;const shifted=g.atoms.map(v=>d.ids.has(v.id)?{...v,x:v.x+sx,y:v.y+sy}:v);if(shifted.every(v=>v.x>=32&&v.x<=768&&v.y>=32&&v.y<=528))updateGraph({...g,atoms:shifted});attach(a.id,candidate.id);}}
 const toolActions=useRef({summon,attach,remove,deleteGroup});toolActions.current={summon,attach,remove,deleteGroup};
 useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools:ModelTool[]=[{name:"get_lab_state",description:"Read atom IDs, symbols, positions, bonds and saved molecule IDs in Alchemist.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({content:[{type:"text",text:JSON.stringify({graph:graphRef.current,saved:Object.keys(savedRef.current),pending:Object.keys(pendingRef.current)})}]})},{name:"summon_atoms",description:"Summon 1 to 12 atoms of a periodic-table element onto the workbench.",inputSchema:{type:"object",properties:{symbol:{type:"string"},count:{type:"integer",minimum:1,maximum:12}},required:["symbol"],additionalProperties:false},execute:args=>{const count=args.count??1;const result=typeof args.symbol==="string"&&Number.isInteger(count)&&Number(count)>=1&&Number(count)<=12?toolActions.current.summon(args.symbol,Number(count)):{ok:false,error:"Invalid element or count"};return {content:[{type:"text",text:JSON.stringify(result)}]};}},{name:"connect_atoms",description:"Connect two existing atom IDs. Valid molecule structures are recognized and saved by the same logic as dragging.",inputSchema:{type:"object",properties:{a:{type:"string"},b:{type:"string"}},required:["a","b"],additionalProperties:false},execute:args=>({content:[{type:"text",text:JSON.stringify(typeof args.a==="string"&&typeof args.b==="string"?toolActions.current.attach(args.a,args.b):{ok:false})}]})},{name:"remove_molecule",description:"Delete the complete connected group containing an existing atom ID from the workbench. Saved collection entries are preserved.",inputSchema:{type:"object",properties:{atomId:{type:"string"}},required:["atomId"],additionalProperties:false},execute:args=>{if(typeof args.atomId!=="string"||!graphRef.current.atoms.some(a=>a.id===args.atomId))return {ok:false,error:"Unknown atom ID"};toolActions.current.deleteGroup(args.atomId);return {ok:true,remainingAtoms:graphRef.current.atoms.length};}}];for(const t of tools){try{void Promise.resolve(context.registerTool({...t,annotations:t.annotations||{readOnlyHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[]);
 const selectedAtom=graph.atoms.find(a=>a.id===selected);const element=elementBySymbol[hoverSymbol];const foundCount=Object.keys(saved).length;const totalFound=new Set([...Object.keys(saved),...Object.keys(pending)]).size;
 const displayCount=labMode==="ionic"?ionicCount:foundCount;const displayTotal=labMode==="ionic"?IONIC_COMPOUNDS.length:MOLECULES.length;
 const selectedGroup=selected?components(graph).find(c=>c.atoms.some(a=>a.id===selected)):null;const selectedMolecule=selectedGroup?matchMolecule(selectedGroup,true)?.molecule:null;
 const visibleMolecules=MOLECULES.filter(m=>(catalogFilter==="all"||(catalogFilter==="isomers"?isomerFamily(m).length>1:saved[m.id]||pending[m.id]))&&(`${m.name} ${m.english} ${m.formula} ${molecularFormula(m)}`).toLowerCase().includes(search.toLowerCase()));
 return <TooltipProvider delayDuration={200}><div className="app-shell" onPointerDownCapture={()=>unlockSound()} onKeyDownCapture={()=>unlockSound()}>
  <header className="topbar"><a className="brand" href="./" aria-label="Alchemist 실험실"><span className="brand-icon"><AtomIcon size={25}/></span><span>alchemist<span className="brand-dot">.</span></span></a><span className="header-divider"/><span className="header-subtitle">작은 원자로, 새로운 발견을.</span><div className="header-actions"><Popover><PopoverTrigger asChild><Button variant="ghost" size="icon" aria-label={soundOn?"효과음 설정, 켜짐":"효과음 설정, 꺼짐"}>{soundOn&&soundVolume>0?<Volume2 size={18}/>:<VolumeX size={18}/>}</Button></PopoverTrigger><PopoverContent className="sound-popover" align="end"><div><label htmlFor="sound-switch">작은 효과음</label><Switch id="sound-switch" checked={soundOn} onCheckedChange={v=>{setSoundOn(v);configureSound(v,soundVolume);if(v)unlockSound();}}/></div><label htmlFor="sound-level">음량 {Math.round(soundVolume*100)}%</label><Slider id="sound-level" aria-label="효과음 음량" min={0} max={35} step={1} value={[Math.round(soundVolume*100)]} onValueChange={v=>{setSoundVolume(v[0]/100);configureSound(soundOn,v[0]/100);}} disabled={!soundOn}/><p>소환할 때 뽁, 발견할 때 작은 폭죽 소리.</p><Button variant="secondary" size="sm" disabled={!soundOn} onClick={()=>playPop()}>소리 들어보기</Button></PopoverContent></Popover><Button variant="ghost" className="help-button" onClick={()=>setShowHelp(true)}><CircleHelp size={17}/><span>이용 방법</span></Button><Button variant="outline" className="collection-button" onClick={()=>labMode==="ionic"?setIonicCollectionOpen(true):setShowCollection(true)}><BookOpen size={17}/><span>{labMode==="ionic"?"이온 도감":"분자 도감"}</span><span className="count-badge">{displayCount}</span></Button></div></header>
  <main className="main"><div className="page-intro"><div><div className="eyebrow"><span/> THE MOLECULAR PLAYGROUND</div><h1>오늘은 어떤 발견을 할까요?</h1><p>{labMode==="ionic"?"양이온과 음이온의 전하를 맞추고, 결정 속 비율을 발견해 보세요.":"원자를 불러오고, 서로 연결해 보세요. 작은 발견이 쌓여 나만의 도감이 됩니다."}</p></div><div className="progress-summary"><div className="progress-ring" style={{"--progress":`${displayCount/displayTotal*100}%`} as CSSProperties}><FlaskConical size={23}/></div><div><span className="progress-count">{displayCount}<span> / {displayTotal}</span></span><span className="progress-caption">{labMode==="ionic"?"발견한 이온 화합물":"발견한 분자"}</span></div></div></div>
  <nav className="bond-mode-switch" aria-label="결합 실험 모드"><button aria-pressed={labMode==="covalent"} onClick={()=>setLabMode("covalent")}>공유 결합<span>분자 만들기</span></button><button aria-pressed={labMode==="ionic"} onClick={()=>setLabMode("ionic")}>이온 결합<span>전하 맞추기</span><i>NEW</i></button></nav>
  <IonicLab active={labMode==="ionic"} collectionOpen={ionicCollectionOpen} onCollectionOpenChange={setIonicCollectionOpen} onCountChange={setIonicCount}/>
  <div hidden={labMode!=="covalent"}>
  <div className="lab-layout"><section className="workbench panel" aria-label="원자 실험 작업대"><div className="panel-heading"><div className="panel-title"><FlaskConical size={18}/><h2>실험 공간</h2><span className="live-pill"><i/>자유 실험</span></div><div className="workbench-actions"><Button variant="ghost" size="sm" disabled={!selectedMolecule} onClick={()=>selectedMolecule&&setModelMolecule(selectedMolecule)}><Rotate3D size={16}/>3D 보기</Button><Button variant="outline" size="sm" className="clear-workbench" disabled={!graph.atoms.length} onClick={()=>setShowClear(true)}><Trash2 size={15}/>전체 비우기</Button></div></div>
   <div className={`canvas-wrap ${dragging?"dragging":""}`}><div className="canvas-label"><span className="tiny-cross">+</span> WORKSPACE <span className="canvas-label-rule"/></div>
   {!graph.atoms.length&&<div className="empty-workspace"><div className="ghost-orbits"><MiniMolecule large symbols={["?","?","?"]}/></div><h3>호기심 하나면 충분해요.</h3><p>오른쪽 주기율표에서 원소를 클릭해<br/>첫 번째 원자를 불러와 보세요.</p><span className="empty-arrow"><ArrowDownLeft size={18}/> 힌트는 한 단계씩 열어 보세요</span></div>}
   <svg ref={svg} className={`atom-canvas ${settling?"settling":""}`} viewBox="0 0 800 560" role="group" aria-label="드래그하거나 원자를 선택해 연결할 수 있는 작업대" onPointerDown={()=>{setSelected(null);setBondMode(false);}}>
    <defs><filter id="atom-shadow" x="-50%" y="-50%" width="200%" height="200%"><feDropShadow dx="0" dy="5" stdDeviation="5" floodColor="#554a7c" floodOpacity=".09"/></filter></defs>
    {graph.bonds.map((b,i)=>{const a=graph.atoms.find(v=>v.id===b.a)!,z=graph.atoms.find(v=>v.id===b.b)!;const l=Math.hypot(z.x-a.x,z.y-a.y)||1;return <g key={`${b.a}-${b.b}`} className="bond" role="button" tabIndex={0} aria-label={`${a.symbol}와 ${z.symbol}의 ${b.order}중 결합 끊기`} onPointerDown={e=>e.stopPropagation()} onClick={()=>process({...graphRef.current,bonds:graphRef.current.bonds.filter(e=>e!==b)})} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();process({...graphRef.current,bonds:graphRef.current.bonds.filter(v=>v!==b)});}}}><line x1={a.x} y1={a.y} x2={z.x} y2={z.y} stroke="transparent" strokeWidth="22"/>{Array.from({length:b.order},(_,n)=>{const off=(n-(b.order-1)/2)*7;return <line key={n} x1={a.x-(z.y-a.y)/l*off} y1={a.y+(z.x-a.x)/l*off} x2={z.x-(z.y-a.y)/l*off} y2={z.y+(z.x-a.x)/l*off} stroke="#b7adcf" strokeWidth="4" strokeLinecap="round"/>;})}</g>;})}
    {graph.atoms.map(a=>{const colors=atomColors(a.symbol);const isSelected=selected===a.id;return <g key={a.id} transform={`translate(${a.x} ${a.y})`} className={`atom ${isSelected?"selected":""} ${near===a.id?"snap-target":""}`} role="button" tabIndex={0} aria-label={`${elementBySymbol[a.symbol].name} 원자${isSelected?", 선택됨":""}`} onPointerDown={e=>startDrag(e,a.id)} onPointerMove={moveDrag} onPointerUp={e=>endDrag(e)} onPointerCancel={e=>endDrag(e,true)} onKeyDown={e=>{if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();if(e.shiftKey)remove([a.id]);else deleteGroup(a.id);}else if(e.key==="Enter"||e.key===" "){e.preventDefault();if(bondMode&&selected&&selected!==a.id)attach(selected,a.id);else setSelected(a.id);}else if(e.key==="Escape"){setSelected(null);setBondMode(false);}else if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();moveGroup(a.id,e.key==="ArrowLeft"?-15:e.key==="ArrowRight"?15:0,e.key==="ArrowUp"?-15:e.key==="ArrowDown"?15:0);}}}><circle className="atom-hit-area" r="45" fill="transparent"/><circle className="atom-halo" r="37" fill="none" stroke={isSelected||near===a.id?"#a28be8":"transparent"} strokeDasharray="3 5" strokeWidth="1.5"/><circle r="29" fill={colors.background} stroke={colors.stroke} strokeWidth="1.7" filter="url(#atom-shadow)"/><text textAnchor="middle" dominantBaseline="central" fill={colors.ink} fontSize="24" fontWeight="650">{a.symbol}</text></g>;})}
    <g transform="translate(710 477)" className={`trash-target ${dragging?"active":""}`} pointerEvents="none"><rect width="72" height="65" rx="15" fill={dragging?"#fff1f2":"#f1f1f7"} stroke={dragging?"#daabb8":"#e4e4ed"} strokeDasharray="4 4"/><path d="M27 22h18m-15 0 1 20h10l1-20M33 18h6m-4 10v9m4-9v9" fill="none" stroke={dragging?"#c56a7b":"#a3a1b3"} strokeWidth="1.5" strokeLinecap="round"/><text x="36" y="56" textAnchor="middle" fontSize="12" fill="#8d889f">삭제</text></g>
   </svg>
   {selectedAtom&&<div className="selected-toolbar"><span className="selected-symbol">{selectedAtom.symbol}</span><span className="selected-label">{selectedMolecule?.name||elementBySymbol[selectedAtom.symbol].name}</span><Tooltip><TooltipTrigger asChild><Button size="icon-sm" variant={bondMode?"secondary":"ghost"} aria-label="선택한 원자와 연결할 원자 선택" onClick={()=>setBondMode(v=>!v)}><Link2 size={16}/></Button></TooltipTrigger><TooltipContent>연결할 원자 선택</TooltipContent></Tooltip><Tooltip><TooltipTrigger asChild><Button size="icon-sm" variant="ghost" aria-label="선택한 원자의 결합 모두 끊기" onClick={()=>detach(selectedAtom.id)}><Unlink size={16}/></Button></TooltipTrigger><TooltipContent>결합 끊기</TooltipContent></Tooltip><span className="toolbar-divider"/><Button size="icon-sm" variant="ghost" aria-label="선택한 원자 하나 삭제" onClick={()=>remove([selectedAtom.id])}><X size={16}/></Button><Button className="delete-group-button" size="sm" variant="secondary" onClick={()=>deleteGroup(selectedAtom.id)}><Trash2 size={14}/>{selectedGroup&&selectedGroup.atoms.length>1?"분자 삭제":"원자 삭제"}</Button></div>}
   {selectedMolecule&&<button className="geometry-badge" onClick={()=>setModelMolecule(selectedMolecule)}><Rotate3D size={15}/><span>{selectedMolecule.name} · {geometryLabel(selectedMolecule)}</span><span>3D ↗</span></button>}
   {selectedGroup&&selectedGroup.atoms.length>1&&!selectedMolecule&&!bondMode&&<div className="structure-status">아직 도감에 없는 구조예요. 원자를 더 연결하거나 결합을 바꿔 보세요.</div>}
   {bondMode&&<div className="connect-message">연결할 다른 원자를 클릭하세요. <button onClick={()=>setBondMode(false)}>취소</button></div>}
   </div><div className="workbench-footer"><span><MousePointer2 size={14}/> 가까이 놓아 연결 · 완성하면 구조 자동 정돈</span><span className="atom-counter">{graph.atoms.length} atoms</span></div>
  </section>
  <section className="periodic-panel panel" aria-label="원소 주기율표"><div className="panel-heading"><div className="panel-title"><AtomIcon size={18}/><h2>원소 주기율표</h2></div><span className="panel-caption">클릭해서 소환</span></div><div className="element-preview"><div className="element-preview-tile" style={{background:categories[element.category].background,color:categories[element.category].ink}}><span>{element.number}</span><strong>{element.symbol}</strong></div><div><h3>{element.name}<span>{element.symbol}</span></h3><p>{categories[element.category].name} <span>·</span> {valences[element.symbol]?"도감 속 분자에 사용되는 원소":"자유롭게 불러올 수 있어요"}</p></div><Plus size={18}/></div>
  <div className="periodic-scroll"><div className="periodic-table"><div className="table-note"><span>118 ELEMENTS.</span><strong>무한한 호기심의 시작.</strong></div>{Array.from({length:18},(_,i)=><span key={`group-${i}`} className="group-number" style={{gridColumn:i+1,gridRow:1}}>{i+1}</span>)}{ELEMENTS.map(e=><Tooltip key={e.symbol}><TooltipTrigger asChild><button className={`element-cell ${hintLevel>=2&&hint.atoms.includes(e.symbol)?"hint-element":""}`} style={{gridColumn:e.col,gridRow:e.row+1,background:categories[e.category].background,color:categories[e.category].ink} as CSSProperties} aria-label={`${e.number} ${e.name} ${e.symbol} 소환`} onClick={()=>summon(e.symbol)} onMouseEnter={()=>setHoverSymbol(e.symbol)} onFocus={()=>setHoverSymbol(e.symbol)}><span>{e.number}</span><strong>{e.symbol}</strong></button></TooltipTrigger><TooltipContent>{e.name} · 클릭하면 원자 1개 소환</TooltipContent></Tooltip>)}<span className="series-marker" style={{gridColumn:3,gridRow:7}}>57–71</span><span className="series-marker" style={{gridColumn:3,gridRow:8}}>89–103</span><span className="series-label" style={{gridColumn:"1 / 3",gridRow:10}}>란타넘족</span><span className="series-label" style={{gridColumn:"1 / 3",gridRow:11}}>악티늄족</span></div></div>
  <div className="element-legend">{Object.entries(categories).map(([id,c])=><span key={id}><i style={{background:c.ink}}/>{c.name}</span>)}</div><div className="periodic-footnote"><span/>분자 도감은 H · C · N · O · F · P · S · Cl · Br · I를 사용해요.</div></section></div>
  <div className="below-lab"><section className="hint-strip staged-hint"><span className="hint-icon"><Lightbulb size={22}/></span><div className="staged-hint-copy"><span className="hint-eyebrow">도전 No. {String(MOLECULES.indexOf(hint)+1).padStart(2,"0")} · 힌트 {hintLevel}/4</span><h3>{hintLevel?HINT_TITLES[hintLevel-1]:"스스로 발견하고, 조금씩 도움받기"}</h3><p>{hintText(hint,hintLevel)}</p></div><div className="staged-hint-actions"><Button variant="secondary" size="sm" onClick={()=>hintLevel<4?advanceHint(hint):setDetail(hint)}>{hintLevel===0?"첫 힌트":hintLevel<4?"다음 단계":"연결 지도"}<ArrowRight size={14}/></Button><Button variant="ghost" size="sm" onClick={nextChallenge}>다른 분자</Button></div></section><section className="collection-strip"><div className="collection-strip-icon"><BookOpen size={22}/></div><div><h3>나만의 분자 도감</h3><p>{totalFound?`${totalFound}종의 발견을 모았어요. 다음 분자는 무엇일까요?`:"아직 빈 페이지, 곧 발견으로 채워질 거예요."}</p></div><Button variant="ghost" size="icon" aria-label="분자 도감 열기" onClick={e=>{e.stopPropagation();setShowCollection(true);}}><ArrowRight size={18}/></Button></section></div>
  <footer className="page-footer"><span><span className="footer-mark">✳</span> 작은 연결이, 새로운 세상을 만듭니다.</span><button className={`sync-status ${saveError?"error":""}`} onClick={()=>{if(saveError)void retrySaving();else setShowCollection(true);}}>{saving||loading?<Loader2 size={14} className="animate-spin"/>:saveError?<TriangleAlert size={14}/>:<HardDrive size={14}/>} {loading?"도감 불러오는 중":saving?"도감 저장 중":saveError?"브라우저 저장 확인 · 다시 시도":"이 브라우저에 저장"}</button></footer>
  {saveError&&<div className="save-notice" role="status">{saveError}{Object.keys(pending).length>0&&" 저장 대기 중인 발견은 창을 닫으면 사라질 수 있어요."}<Button size="sm" variant="outline" onClick={()=>void retrySaving()}>다시 시도</Button></div>}
  </div></main>
  <Dialog open={!!celebration} onOpenChange={v=>{if(!v)setCelebration(null);}}><DialogContent showCloseButton={false} className="discovery-dialog">{celebration&&<><Fireworks/><DialogHeader><div className="discovery-kicker"><Sparkles size={16}/> 분자를 발견했어요</div><DialogTitle className="discovery-name">{celebration.molecule.name}</DialogTitle><DialogDescription className="discovery-english">{celebration.molecule.english}</DialogDescription></DialogHeader><div className="discovery-formula">{celebration.molecule.formula}</div><p className="discovery-description">{celebration.molecule.description}</p><div className="discovery-saved">{saved[celebration.molecule.id]?<><Check size={16}/> 분자 도감에 저장되었어요</>:<>{saving?<Loader2 size={16} className="animate-spin"/>:<TriangleAlert size={16}/>} {saving?"도감에 저장하는 중":"저장 대기 중 · 저장 설정을 확인해 주세요"}</>}</div><DialogClose asChild><Button className="continue-button">계속 실험하기<ArrowRight size={16}/></Button></DialogClose><button className="discovery-collection-link" onClick={()=>openDiscoveredCollection(celebration.molecule.id)}>분자 도감에서 보기</button></>}</DialogContent></Dialog>
  <Sheet open={showCollection} onOpenChange={v=>{setShowCollection(v);if(!v)setCollectionTarget(null);}}><SheetContent onOpenAutoFocus={event=>{if(collectionTarget)event.preventDefault();}} className="collection-sheet" showCloseButton={false}><SheetHeader><div className="sheet-title-row"><BookOpen size={21}/><SheetTitle>나의 분자 도감</SheetTitle><SheetClose asChild><Button size="icon" variant="ghost" aria-label="도감 닫기"><X size={19}/></Button></SheetClose></div><SheetDescription>이 브라우저에 자동 저장돼요. 우연한 연결을, 나만의 발견으로.</SheetDescription></SheetHeader><div className="collection-progress"><div><strong>{foundCount}<span> / {MOLECULES.length}</span></strong><span>저장한 분자</span></div><div className="progress-track"><i style={{width:`${foundCount/MOLECULES.length*100}%`}}/></div></div><div className="collection-tools"><div className="collection-search"><Search size={16}/><Input placeholder="이름 또는 화학식 검색" value={search} onChange={e=>setSearch(e.target.value)} aria-label="분자 도감 검색"/></div><div className="collection-filters"><Button size="sm" variant={catalogFilter==="all"?"secondary":"ghost"} onClick={()=>setCatalogFilter("all")}>전체 {MOLECULES.length}</Button><Button size="sm" variant={catalogFilter==="found"?"secondary":"ghost"} onClick={()=>setCatalogFilter("found")}>발견한 분자 {totalFound}</Button><Button size="sm" variant={catalogFilter==="isomers"?"secondary":"ghost"} onClick={()=>setCatalogFilter("isomers")}>이성질체</Button></div></div><div ref={collectionGridRef} className="collection-grid">{loading&&<p className="collection-empty"><Loader2 className="animate-spin"/> 도감을 불러오는 중이에요.</p>}{!loading&&visibleMolecules.length===0&&<div className="collection-empty"><AtomIcon size={36}/><p>{search?"검색 결과가 없어요.":"첫 번째 발견을 기다리고 있어요."}</p><Button variant="secondary" onClick={()=>{setShowCollection(false);setHint(MOLECULES.find(m=>!saved[m.id]&&!pending[m.id])||MOLECULES[0]);}}>실험하러 가기<ArrowRight size={16}/></Button></div>}{!loading&&visibleMolecules.map((m,i)=>{const known=!!saved[m.id]||!!pending[m.id];return <button key={m.id} data-collection-id={m.id} className={`molecule-card ${known?"found":"locked"} ${collectionTarget===m.id?"collection-target":""}`} onClick={()=>setDetail(m)}><div className="molecule-card-top"><span>No. {String(MOLECULES.indexOf(m)+1).padStart(2,"0")}</span>{known?<Check size={15}/>:<LockKeyhole size={14}/>}</div><div className="molecule-card-formula">{known?m.formula:"?"}</div><strong>{known?m.name:"아직 발견하지 못했어요"}</strong><span className="molecule-card-caption">{known?(pending[m.id]?"저장 대기 중":m.family):"클릭해서 힌트 보기"}</span></button>;})}</div>{saveError&&<div className="sheet-error"><TriangleAlert size={16}/><p>{saveError}</p><Button size="sm" variant="outline" onClick={()=>void retrySaving()}>다시 시도</Button></div>}</SheetContent></Sheet>
  <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className={`molecule-detail ${detail&&(saved[detail.id]||pending[detail.id])?"unlocked-detail":""}`}><DialogHeader><DialogTitle>{detail&&(saved[detail.id]||pending[detail.id])?detail.name:`도전 No. ${detail?String(MOLECULES.indexOf(detail)+1).padStart(2,"0"):""}`}</DialogTitle><DialogDescription>{detail&&(saved[detail.id]||pending[detail.id])?`${detail.english} · ${detail.formula}`:"원하는 만큼만 힌트를 열어 보세요."}</DialogDescription></DialogHeader>{detail&&((saved[detail.id]||pending[detail.id])?<><MoleculeViewer key={detail.id} molecule={detail} compact/><p>{detail.description}</p><SubstancePhoto key={detail.id} id={detail.id} name={detail.name}/><IsomerFamily molecule={detail} known={id=>!!saved[id]||!!pending[id]} onSelect={setDetail}/><div className="molecule-facts"><div className="phase-badge">{MOLECULE_INFO[detail.id].phase}<span>25°C · 약 1기압 기준</span></div><section><h3>물리적 특징</h3><p>{MOLECULE_INFO[detail.id].physical}</p></section><section><h3>화학적 특징</h3><p>{MOLECULE_INFO[detail.id].chemical}</p></section><div className="fact-sources">{infoSources(MOLECULE_INFO[detail.id]).map(link=><a key={link.url} href={link.url} target="_blank" rel="noreferrer">{link.label} ↗</a>)}</div></div>{saved[detail.id]&&<p className="discovery-date">발견한 날 · {new Date(saved[detail.id].discoveredAt).toLocaleDateString("ko-KR")}</p>}<Button onClick={()=>summonMolecule(detail)}><Plus size={16}/>이 분자를 작업대에 소환</Button></>:<><HintSteps molecule={detail} level={hintLevels[detail.id]||0} onAdvance={()=>advanceHint(detail)}/><Button onClick={()=>{setHint(detail);setDetail(null);setShowCollection(false);}}>이 도전을 작업대에서 계속하기<ArrowRight size={16}/></Button></>)}</DialogContent></Dialog>
  <Dialog open={!!modelMolecule} onOpenChange={v=>{if(!v)setModelMolecule(null);}}><DialogContent className="model-dialog"><DialogHeader><DialogTitle>{modelMolecule?.name} · 3D 보기</DialogTitle><DialogDescription>{modelMolecule?.formula} · 같은 연결 구조를 입체적으로 살펴보세요.</DialogDescription></DialogHeader>{modelMolecule&&<MoleculeViewer key={modelMolecule.id} molecule={modelMolecule}/>}</DialogContent></Dialog>
  <Dialog open={showHelp} onOpenChange={setShowHelp}><DialogContent className="help-dialog"><DialogHeader><div className="help-icon"><AtomIcon size={28}/></div><DialogTitle>원자에서 시작하는 작은 발견</DialogTitle><DialogDescription>정답을 외우기보다, 직접 연결해 보세요.</DialogDescription></DialogHeader><ol className="help-steps"><li><span>01</span><div><h3>클릭해 불러오기</h3><p>주기율표의 원소를 누를 때마다 원자가 하나씩 소환돼요.</p></div></li><li><span>02</span><div><h3>가까이 놓아 연결하기</h3><p>원자를 다른 원자 가까이에 끌어다 놓으세요. 연결된 원자들은 함께 움직여요. 원자를 선택한 뒤 연결 버튼으로 다른 원자를 눌러도 돼요. 같은 묶음의 두 끝을 연결해 고리를 만들 때도 이 버튼을 사용하세요.</p></div></li><li><span>03</span><div><h3>발견하고, 모으기</h3><p>도감에 있는 분자의 연결 구조가 완성되면 이름이 나타나고 자동 저장돼요. 이중·삼중 결합은 구조에 맞춰 자동으로 조정돼요.</p></div></li><li><span>04</span><div><h3>마음껏 다시 실험하기</h3><p>결합선을 누르면 연결이 끊어져요. 연결된 분자를 휴지통에 놓거나 ‘분자 삭제’를 누르면 묶음으로 삭제돼요. × 버튼은 원자 하나만 지워요. 위쪽 ‘전체 비우기’는 모든 원자와 결합을 지워요. 키보드는 Delete로 분자 삭제, Shift+Delete로 원자 하나 삭제, 화살표로 묶음 이동이 가능해요.</p></div></li></ol><div className="science-note"><strong>실제 화학을 바탕으로 한 구조 퍼즐</strong><p>{MOLECULES.length}종의 중성 공유 결합 분자를 지원해요. 완성한 분자는 자동 정돈되고, 3D 보기에서 회전할 수 있어요. 물·이산화 탄소 외의 모형은 결합 구조를 바탕으로 이상화한 교육용 근사입니다. 이온 결합은 상단의 별도 모드에서 실험할 수 있어요. 실제 반응 조건, 전자 분포와 금속 결정은 재현하지 않아요. 미등록 구조가 화학적으로 불가능하다는 뜻은 아니에요. 원자의 연결 순서로 구조 이성질체를 구분해요. 입체 이성질체와 공명 구조는 별도 발견으로 나누지 않아요.</p><p>작업대는 새로고침하면 비워지고, 저장된 도감은 이 브라우저에 남아요. 사이트 데이터를 삭제하거나 시크릿 모드를 닫으면 기록이 사라질 수 있어요. 다른 기기와는 동기화되지 않아요.</p><a href="https://iupac.org/what-we-do/periodic-table-of-elements/" target="_blank" rel="noreferrer">IUPAC 주기율표 ↗</a><a href="https://pubchem.ncbi.nlm.nih.gov/" target="_blank" rel="noreferrer">PubChem 분자 정보 ↗</a></div></DialogContent></Dialog>
  <AlertDialog open={showClear} onOpenChange={setShowClear}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>새로운 실험을 시작할까요?</AlertDialogTitle><AlertDialogDescription>작업대의 원자와 결합을 모두 지웁니다. 발견한 분자 도감은 그대로 남아요.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><AlertDialogAction onClick={clear}>작업대 비우기</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster position="bottom-center" theme="light" richColors closeButton/>
 </div></TooltipProvider>;
}
